import type { Metadata } from "next";
import "./globals.css";
import { GlobalProvider } from "@/components/Provider/GlobalProvider/GlobalProvider";
import Header from "@/components/Header/Header";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
          <Suspense>
            {children}
          </Suspense>
        </GlobalProvider>
      </body>

    </html>
  );
}
